NVIDIA/gpu-driver-container

rhel9/Dockerfile
This fixes some CVEs recently reported from the go version used
=> [rhel9] update golang version to 1.22.1

.nvidia-ci.yml
Hi again 👋🏻 ,
migrating this PR from Gitlab as suggested by @ArangoGutierrez.
As you're apparently planning to migrate to the main repo from Gitlab to Github (including CICD?), this PR might be obsolete at this point. Also, as already mentioned in the original PR on Gitlab which is no longer available, I'm not quite sure if the jobs/steps defined in the `.nvidia-ci.yml` are being used anywhere, as there is no direct include in the main gitlab ci file.
If it is used to build the images for NGC, this PR _should_ be adding the images for RHEL9 if I understood the setup correctly.
As said, this might be obsolete at this point, so feel free to close this PR if it is no longer required.
=> fix: add missing rhel9 ngc ci steps

centos7/nvidia-driver, rhel8/nvidia-driver, rhel9/nvidia-driver
Same changes as #15 but for `centos7` and `rhel9`. Also includes quoting of paths to avoid word splitting and globs as per shellcheck best practices
See [here](https://github.com/koalaman/shellcheck/wiki/SC2046) for more details on the shellcheck fix
=> don't hardcode arch dir when symlinking mellanox ofa_kernel headers

rhel9/nvidia-driver
A number of changes made to the rhel8 container did not make it to rhel9. This PR should bridge that gap
=> sync the rhel9 driver container with the latest changes in rhel8

ubuntu22.04/Dockerfile
gcc-12 is needed for the more recent kernel versions - 5.19.x and 6.5.x. We have also found that gcc-12 is backwards compatible with kernels that have been compiled against gcc-11
This change is limited to Ubuntu 22.04 as `gcc-12` is not available as a package in Ubuntu 20.04
=> [Ubuntu 22.04] Install gcc-12 in the driver container build phase

.common-ci.yml, .github/workflows/image.yaml, .gitlab-ci.yml, .nvidia-ci.yml, Makefile, ci/localbuild.sh, ci/run.sh, multi-arch.mk, rhel8/Dockerfile, rhel9/Dockerfile, ubuntu20.04/Dockerfile, ubuntu22.04/Dockerfile, versions.mk, vgpu/src/go.mod, vgpu/src/go.sum
As cuda version `12.4.1` is no longer available for `centos`, we remove support for centos
=> remove centos7 support, bump cuda and go versions

.common-ci.yml, .github/workflows/image.yaml
The precompiled driver packages for R550 in ubuntu22.04 are now live
https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=linux-modules-nvidia-550-server&searchon=names
=> [ubuntu22.04] add R550 precompiled driver containers

.common-ci.yml, .github/workflows/image.yaml
Canonical regularly publishes. Oracle-flavoured Ubuntu precompiled nvidia driver packages. We should take advantage of this in our precompiled driver publish pipelines
[R550 Precompiled driver container for Ubuntu22.04](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=linux-objects-nvidia-550-5.15.0-1058-oracle&searchon=names)
[R535 Precompiled driver container for Ubuntu22.04](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=linux-objects-nvidia-530-5.15.0-1058-oracle&searchon=names)
Signed-off-by: Tariq Ibrahim <tibrahim@nvidia.com>
=> [Ubuntu 22.04] build precompiled driver containers for the oracle flavour

vgpu-manager/rhel8/nvidia-driver, vgpu-manager/ubuntu20.04/nvidia-driver, vgpu-manager/ubuntu22.04/nvidia-driver
See NVBug 4653463 for more details.
=> vGPU Manager fixes required for vGPU 17.2

azurelinux/Dockerfile, azurelinux/nvidia-driver
Onboard the libnvidia-nscq RPM published by the Azure Linux team for the Azure Linux precompiled driver container
=> Add libnvidia-nscq for Azure Linux

.common-ci.yml, .nvidia-ci.yml, scripts/precompiled.sh
=> add ngc signing job for auto signing

azurelinux/Dockerfile
NVIDIA GPU driver container will be supported on Azure Linux 3.0. This change modifies the namespace from "CBL-Mariner" to "azurelinux"
=> Target Support to Azure Linux 3.0

.github/workflows/ci.yaml, tests/scripts/.definitions.sh, tests/scripts/checks.sh, tests/scripts/end-to-end-nvidia-driver.sh, tests/scripts/pull.sh, tests/scripts/remote.sh, tests/scripts/uninstall-operator.sh, tests/scripts/verify-operator.sh
TODO--
*1. *
> + matrix:
+ driver:
+ - 535.183.06
+ - 550.90.07
An idea for a potential follow-up – instead of defining a matrix and spinning up one AWS instance per driver version, can we instead pass all driver versions as input to the test script and test all of them in sequence? For example, first install 535.183.06, and then upgrade to 550.90.07? This would also allow us to source the driver versions from the versions.mk file, instead of having to redefine and maintain that list here.
2
+name: CI
Let's rename this to End-to-end tests
3
+# Install the operator with usePrecompiled mode set to true
Remove this comment as it is not accurate.
4
+ AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
I don't believe AWS_SESSION_TOKEN is needed with current holodeck implementation. Let's …
=> end-to-end  gpu driver testing enhancement

sle15/nvidia-driver
I wasn't sure exactly what the local variable in the _resolve_kernel_version function
---
local version=$(zypper -x se -s -t package --match-exact "kernel-devel$package_flavor"  |
grep "solvable "| grep $version_without_flavor | sed -e 's/.*edition="\([^"]*\).*/\1/g;s/\(.*\)\..*/\1/')
---
is trying to return. Since this script, when run against kernel version 5.14.21-150500.55.62-default, only returns the Basesystem repo, I assumed that this was the desired result.
However, when the script is run against kernel version 5.14.21-150500.55.62-default, it sometime returns the both the SLE_BCI and Basesystem repos.
I'm offering a very simple fix  of inserting a grep for "Basesystem" that can be used or can just serve as an example for a more elegant solution.
=> Added  '| grep "Basesystem"' to ensure only one software repo is returned for local variable in the _resolve_kernel_version function

ubuntu22.04/Dockerfile
I've verified that gpg keys in both locations are the same. Updating it here for consistency
=> [ubuntu22.04] use the correct location to fetch cuda repo gpg keys

.nvidia-ci.yml
This change should resolve the following errors seen when attempting to run gitlab pipelines on merge to main
```
Unable to create pipeline
'sign:ngc-precompiled-ubuntu22.04: [535, aws]' job needs 'release:ngc-precompiled-ubuntu22.04: [535, aws]' job, but 'release:ngc-precompiled-ubuntu22.04: [535, aws]' is not in any previous stage
'sign:ngc-precompiled-ubuntu22.04: [535, aws]' job needs 'release:ngc-precompiled-ubuntu22.04: [535, azure]' job, but 'release:ngc-precompiled-ubuntu22.04: [535, azure]' is not in any previous stage
'sign:ngc-precompiled-ubuntu22.04: [535, aws]' job needs 'release:ngc-precompiled-ubuntu22.04: [535, generic]' job, but 'release:ngc-precompiled-ubuntu22.04: [535, generic]' is not in any previous stage
'sign:ngc-precompiled-ubuntu22.04: [535, aws]' job needs …
```
=> run the sign-ngc-precompiled-job only during scheduled CI jobs

.github/workflows/image.yaml, .nvidia-ci.yml
Adding Openshift 4.16 and RHEL 8.10 to supported distros
Remove Openshift 4.9-4.11 and RHEL 8.6, 8.7 and 8.9
=> update matrix of supported distros

rhel8/Dockerfile, rhel9/Dockerfile, ubuntu20.04/Dockerfile, ubuntu22.04/Dockerfile
This will fix the CVE reported here: https://pkg.go.dev/vuln/GO-2024-3107
=> bump golang version to 1.22.7

.github/workflows/precompiled.yaml, tests/cases/nvidia-driver.sh, tests/ci-run-e2e.sh, tests/scripts/ci-precompiled-helpers.sh, tests/scripts/findkernelversion.sh
**Old workflow :** 
1.   Build local image  and push image to the repo 
2.   e2e tests  
a. upgrade kernel 
b. fetch repo image on target with helm install to run driver tests
**New Workflow:**
Build Local Image
a. Build the image
a. Save the built image as a .tar file using docker save.
b. Upload the .tar file as an artifact (not to the repo).
e2e Tests
a. Upgrade the kernel on the target.
b. Download the artifact (the saved .tar image file) from the CI pipeline
c. Transfer the .tar image to the target using rsync.
d. Import the .tar image on the target using the ctr command.
e. Run helm install to execute driver tests.
Publish or Push Image to Repo
a. Download the artifact.
b. Load the .tar image using docker load.
c. Push the image to the repo using docker push.
=> enhance e2e test and publish image

rhel8/precompiled/Dockerfile, rhel9/precompiled/Dockerfile, ubuntu20.04/precompiled/Dockerfile, ubuntu22.04/precompiled/Dockerfile, vgpu-manager/rhel8/Dockerfile, vgpu-manager/ubuntu20.04/Dockerfile, vgpu-manager/ubuntu22.04/Dockerfile
TODO: Investigate why dependabot doesn't open PRs for these
=> bump cuda base image versions in precompiled driver images

ubuntu24.04/Dockerfile, ubuntu24.04/install.sh, ubuntu24.04/nvidia-driver
This change condenses the two-step driver install into a single step. 
Currently, the driver image installs the userspace components and kernel modules separately. This was to allow for signing of the kernel modules with a custom private key and then relinking the signed kernel modules as well as updating the Kernel module should the underlying kernel host be updated. 
As none of these workflow apply today, we simplify the driver installation and allow for defining an API in gpu-operator where users can easily pass custom runfile installation arguments
I have tested Driver upgrades and updates (both Open and ClosedRM modules) with these changes and the driver container has been running with no issues
=> [Ubuntu24.04] Install the driver in a single step

ubuntu24.04/Dockerfile
This PR fixes the following warning observed when running the ubuntu24.04 gpu driver container
`W: Download is performed unsandboxed as root as file '/tmp/tmp.t07XczEtx1/linux-image-6.8.0-47-generic_6.8.0-47.47_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`
This is consistent with the driver containers for the other OS versions
=> [ubuntu24.04] grant _apt user root privileges

ubuntu24.04/precompiled/Dockerfile
This fixes the following warning messages:
```
9.999 W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list.d/ubuntu.sources:1
9.999 W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list.d/ubuntu.sources:1
9.999 W: Target Packages (universe/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list.d/ubuntu.sources:1
9.999 W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list.d/ubuntu.sources:1
9.999 W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:2 and …
```
=> [ubuntu24.04-precompiled] remove redundant apt sources config

ubuntu22.04/precompiled/Dockerfile, ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/precompiled/Dockerfile, ubuntu24.04/precompiled/nvidia-driver
We have found that the OpenRM modules fail to load successfully as it's unable to find the firmware files in the `/lib/firmware` directory. This was happening due to two reasons:
1. The `/lib/firmware` files were being installed during the container image build-time. See [here](https://github.com/NVIDIA/gpu-driver-container/blob/aca3aca650f3a6c3d465d7bb6606b2c074abde76/ubuntu22.04/precompiled/Dockerfile#L52)
2. The `/lib/firmware` files were wiped out as we mount the `/run/nvidia/driver/lib/firmware` directory . See [here](https://github.com/NVIDIA/gpu-operator/blob/main/assets/state-driver/0500_daemonset.yaml#L133-L134)
To fix this issue, we make the following changes
1. We only download (and not install) the `nvidia-driver-${DRIVER_BRANCH}-server` package, so that the actual takes place …
=> fix precompiled driver container failures when enabling OpenRM

ubuntu24.04/nvidia-driver
With this change, the ubuntu24.04 will select the recommended kernel module type for a driver version and the gpu device. It also provides users the option to explicitly set a desired kernel module type.
~We also replace the -m flag with the --kernel-module-type as the former is deprecated. See below (taken from the nvidia-installer CLI help text)~ UPDATE: It looks like `--kernel-module-type` is a new flag and is only available from R560 onwards. So we can only add this flag after R535 and R550 are EOL'ed
```
-M KERNEL-MODULE-TYPE, --kernel-module-type=KERNEL-MODULE-TYPE
The type of kernel modules to build and install. Valid values are "open" and "proprietary".
-m KERNEL-MODULE-BUILD-DIRECTORY, --kernel-module-build-directory=KERNEL-MODULE-BUILD-DIRECTORY
Directly set the directory within …
```
=> [ubuntu24.04] use KERNEL_MODULE_TYPE envar in place of OPEN_KERNEL_MODULES_ENABLED

ubuntu20.04/Dockerfile
The debian package is broken for Ubuntu 20.04 and force installing it introduced a regression. At runtime, we install some prerequisite packages, but apt fails to install them due to the unmet dependencies of the nvidia-imex package.
=> Remove installation of imex pkg on Ubuntu 20.04

.github/dependabot.yml
directories:
- "*"  
Dependabot does not support wildcard * or **/ paths in the directory field. 
docker section will fail silently
=> dependabot update for nested dir

ubuntu22.04/precompiled/Dockerfile, ubuntu22.04/precompiled/local-repo.sh, ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/precompiled/Dockerfile, ubuntu24.04/precompiled/local-repo.sh
This PR introduces a completely new method of installing the nvidia precompiled driver packages. 
We recently discovered that our offline installs weren't exactly "offline". During the driver container run-time, the driver container was still downloading packages externally. The root cause of this was the multiple `apt-get update` calls, which would erase the previously downloaded packages from the `apt-get install -y --no-install-recommends --download-only <packages>` command.
i) Download the packages and its dependencies using the following commands
```
apt-get download $PACKAGE
apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances $PACKAGE | grep "^\w" | sort -u)
```
ii) Move to a permanent location and gzip …
=> [ubuntu-precompiled] enable offline installation of driver packages

.nvidia-ci.yml
Add OCP 4.18 as it is the newest Openshift Version.
Reference: https://access.redhat.com/support/policy/updates/openshift
=> update RH OCP support matrix

ubuntu24.04/precompiled/nvidia-driver
Missed these changes in the ubuntu24.04 directory when implementing the air-gapped installs of the nvidia precompiled driver packages
=> [ubuntu24.04][precompiled] update driver installation steps

rhel8/nvidia-driver, rhel9/nvidia-driver, ubuntu20.04/nvidia-driver, ubuntu22.04/nvidia-driver, ubuntu24.04/nvidia-driver
This aligns with the number of retries we attempt when terminating other userspace processes, like nvidia-persistenced and nv-fabricmanager.
=> Increase number of retries when terminating nvidia-grid process

.common-ci.yml, .nvidia-ci.yml
If 'rules' are defined for a Gitlab CI job, then the job will only be added to the pipeline if one of the rules matches. This commit ensures that for scheduled pipelines, at least one rule matches for the precompiled jobs which are meant to run on the schedule.
=> [ci] fix internal precompiled jobs

.github/workflows/precompiled.yaml, tests/scripts/ci-precompiled-helpers.sh, tests/scripts/findkernelversion.sh
_Removed downloading of kernel_version.txt from the Docker base.
Now, artifacts-based download is considered instead.
Reason: When building the base via make build-base-jammy, it now includes two LTS kernels (Ubuntu 22.04: 5.15 and 6.8). Running a parallel matrix will cause make build-base-jammy to overwrite( 5.15 and 6.8) kernel-version.txt, leading to incorrect values in matrix_values files during download with regctl in determine-e2e-test-matrix job. with regctl command we are downloading kernel_version.txt file from docker base. 
Solution: Either modify the Makefile to introduce a new command (make build-base-${base_target}-${lts_kernel}) or directly download kernel_version.txt from artifacts.
Since kernel_version... files are already being uploaded as artifacts, we now rely on those …
=> Precompile kernel version fix for multiple base target

rhel8/nvidia-driver, rhel9/nvidia-driver, ubuntu20.04/nvidia-driver, ubuntu22.04/nvidia-driver
This reverts commit efd73d849fb88bacd5ed8438f53bcb85c7acab82.
With the next gpu-operator release on the horizon, we no longer need to maintain this backcompat logic. All future driver containers will utilise the KERNEL_MODULE_TYPE env var going forward
=> Revert "Reintroduce OPEN_KERNEL_MODULES_ENABLED envvar for backwards compatibility"

.common-ci.yml, .github/workflows/image.yaml, .github/workflows/precompiled.yaml, Makefile, scripts/precompiled.sh
multiple lts kernel support for base image for precompiled driver image
=> base image precompiled multi lts_kernel  support

ubuntu22.04/precompiled/Dockerfile, ubuntu22.04/precompiled/local-repo.sh, ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/precompiled/Dockerfile, ubuntu24.04/precompiled/local-repo.sh, ubuntu24.04/precompiled/nvidia-driver
As of gpu-operator v25.3.0, we no longer set the `OPEN_KERNEL_MODULES_ENABLED` variable and it is replaced by the `KERNEL_MODULE_TYPE` variable. This PR brings the precompiled containers to parity with the runfile ones
=> [ubuntu-precompiled] add support for the KERNEL_MODULE_TYPE env var

vgpu-manager/ubuntu22.04/Dockerfile
This was fixed in dd69782dc6a21aa92ded68fb9db58bd4b1a23a4a (cc @tariq1890) for regular installs, but vgpu-manager still fails to compile drivers in Ubuntu22.04 with Kernels in 5.19.x/6.5.x
This fix seemed appropriate and straight-forward enough to simply port it to the vgpu-manager image
=> [vgpu-manager/ubuntu22.04] Install gcc-12 in vgpu driver manager container

.github/workflows/image.yaml, .github/workflows/precompiled.yaml, base/generate-ci-config
1. LTS Kernel Matrix: Added support for 5.15 and 6.8 for (ubuntu22.04)
2. Base Target and LTS KERNEL Version Matrix: Added support for Jammy and Noble.
3. Hardcoded Values Removed: 
_base_target_ubuntu22_04, base_target_ubuntu24_04, and lts_kernel_ubuntu24_04 are now dynamically handled instead of being hardcoded._
=> ubuntu22.04 6.8 kernel support

ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/precompiled/nvidia-driver
This was missed in the precompiled driver containers when implementing NVLink5+ support.
=> [ubuntu-precompiled] stop nvlsm.pid before driver startup

rhel8/nvidia-driver, rhel9/nvidia-driver, ubuntu20.04/nvidia-driver, ubuntu20.04/precompiled/nvidia-driver, ubuntu22.04/nvidia-driver, ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/nvidia-driver, ubuntu24.04/precompiled/nvidia-driver, vgpu-manager/rhel8/nvidia-driver, vgpu-manager/ubuntu20.04/nvidia-driver, vgpu-manager/ubuntu22.04/nvidia-driver
This is consistent with the rest of the daemons (gridd, fabric manager, nvlsm) managed by the driver container
=> print the nvidia-persisentenced stop message only if pid is detected

rhel9/nvidia-driver
Starting from RHEL9.3, the `video` module is a pre-requisite for the `nvidia-modeset` kernel module
=> load the video module for RHEL9 with minor versions 3 or greater

.github/workflows/precompiled.yaml
The precompiled.yaml file does not contain logic to update the base image on [ghcr.io](http://ghccr.io/) , it only build the base image and retrieves the latest kernel version .
Added logic to update the base image to 
ghcr.io/nvidia/driver:base-BASE_TARGET-LTS_KERNEL-KERNEL_FLAVOR-driver_branch
=> Publish Base Image

rhel8/install.sh, rhel9/install.sh
The jq package was added in https://github.com/NVIDIA/gpu-driver-container/commit/926a283047e0b03da8a5384ac307aa64e046e41a. The code that invoked jq was subsequently removed in https://github.com/NVIDIA/gpu-driver-container/commit/c9a6afcd4b473a1978c8eeb0f9292d375a0e2154.
=> Remove unused jq package in rhel8 and rhel9 images

ubuntu16.04/nvidia-driver, ubuntu18.04/nvidia-driver, ubuntu20.04/nvidia-driver, ubuntu22.04/nvidia-driver, ubuntu24.04/nvidia-driver, vgpu-manager/ubuntu20.04/nvidia-driver, vgpu-manager/ubuntu22.04/nvidia-driver
The driver container fails to install on kernels of the generic-64k flavor. The root cause is that the [resolve_kernel_version() function](https://github.com/NVIDIA/gpu-driver-container/blob/e9db94520c008aec0bc6279bfbade65600c8135f/ubuntu22.04/nvidia-driver#L47-L61) is stripping the "-64k" suffix from the kernel version string. So when we attempt to install the kernel-header packages, we are installing the wrong version of the packages.
script tested on arm64 target : 
```
./run.sh 6.8.0-51-generic-64k
run.sh 
#!/bin/bash
get_kernel() {
local version=$(apt-cache show "linux-headers-${KERNEL_VERSION}" 2> /dev/null | \
sed -nE 's/^Version:\s+(([0-9]+\.){2}[0-9]+)[-.]([0-9]+).*/\1-\3/p' | head -1)
local flavor=$(echo ${KERNEL_VERSION} | sed 's/[^a-z]*//' | grep -Ev "^generic|virtual")
local …
```
=> Addition of 64k kernel-flavor in KERNEL_VERSION

rhel8/nvidia-driver, rhel9/nvidia-driver
Summary of changes
i) Install `libelf-elfutils` and `libelf-elfutils-devel` packages after the DNF release version is resolved. This was done to support clusters using a custom RHEL RPM package repo
ii) Install `libelf-elfutils` and `libelf-elfutils-devel` packages in separate steps. This is done as the devel packages depend on the former in more recent RHEL versions. Installing the devel package may require downgrading the `libelf-elfutils` package, and serialised installation of the two packages will allow for automatic downgrading and unblock the installation of the devel package
=> install elfutils packages after dnf_releasever is resolved

Makefile, native-only.mk
This PR allows one to run the following make commands to build and push vGPU host driver images. 
```
$ VGPU_HOST_DRIVER_VERSION=570.124.06     IMAGE_NAME=nvcr.io/ea-cnt/nv_only/vgpu-manager     make build-vgpuhost-ubuntu22.04
DOCKER_BUILDKIT=1 \
docker  build --pull \
\
--platform=linux/amd64 \
--tag nvcr.io/ea-cnt/nv_only/vgpu-manager:570.124.06-ubuntu22.04 \
--build-arg DRIVER_TYPE=vgpu \
--build-arg VGPU_LICENSE_SERVER_TYPE=NLS \
--build-arg DRIVER_BRANCH="570" \
--build-arg DRIVER_VERSION="570.124.06" \
--build-arg GOLANG_VERSION="1.24.4" \
--build-arg CVE_UPDATES="" \
--build-arg CUDA_VERSION="" \
\
--file /egx/test/gpu-driver-container/vgpu-manager/ubuntu22.04/Dockerfile \
/egx/test/gpu-driver-container/vgpu-manager/ubuntu22.04
$ VGPU_HOST_DRIVER_VERSION=570.124.06 …
```
=> Add make targets for vGPU host drivers

ubuntu24.04/nvidia-driver
When running `pro attach` on an Ubuntu 24.04 container, we are faced with a strange "chicken & egg" problem as the pro client attempts to use openssl + fips when it detects that the underlying kernel is fips_enabled, however, the FIPS packages are only available after the pro client enables APT repo access to the FIPS packages.
To work around this problem, we explicitly set the env var `OPENSSL_FORCE_FIPS_MODE=0` to unblock the pro client calls. After successful enablement of FIPS mode, we download the OpenSSL FIPS module and unset the `OPENSSL_FORCE_FIPS_MODE` env var
=> [ubuntu24.04][FIPS] disable FIPS enforcement temporarily when enabling pro mode

ubuntu24.04/Dockerfile
TODO: figure out a way to automate updates of the ubuntu 24.04 base image when referenced via a build arg. `dependabot` does not seem to support this, so we many need to consider using `renovate` instead
=> bump ubuntu24.04 base image to noble-20250910

.github/workflows/precompiled.yaml
Sometimes ,new kernel releases or enabling full fledged e2e AWS testing , creates too many instances ( >= 12) . This change will restrict AWS instances to batches of 5 . Once a batch of 5 completes , another batch of upto 5 instances will be created to continue running the e2e tests . 
This will resolve  AWS account instance limit error ( vpcs creation)
=> Restrict e2e runs to 5 instances

ubuntu22.04/precompiled/nvidia-driver, ubuntu24.04/precompiled/nvidia-driver
Fix error in nvidia-driver script: 
Package nvidia-fabricmanager-580 is a virtual package provided by:
nvidia-fabricmanager 580.65.06-1
E: Version '580.65.06-1' for 'nvidia-fabricmanager-580' was not found
E: Version '580.65.06-1' for 'libnvsdm-580' was not found
=> Fix: precompiled R580 package install error
